name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        env:
          PUBLIC_PATH: '/wasm-clang/js/'
        run: yarn build

      - name: Remove symlinks and hard links
        run: |
          find ./public -type l -exec rm {} \;
          find ./public -type f -links +1 -exec rm {} \;

      - name: Check artifact size
        run: du -sh ./public

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
